-- CREATE TABLE IF NOT EXISTS users (
ID SERIAL PRIMARY KEY,
EMAIL VARCHAR(255) UNIQUE NOT NULL,

password TEXT NOT NULL,

FIRST_NAME VARCHAR(255),
LAST_NAME VARCHAR(255),
CONTACT_NUMBER VARCHAR(100),
ADDRESS VARCHAR(255)

-- );